(ns baleen-wikipedia.util
  (:import [java.net URLDecoder URL MalformedURLException]
           [org.jsoup Jsoup])
  (:require [clojure.string :as string]))
      
(defn href-to-url [text]
  "Convert an href from an <a>, as found in HTML, to a URL. Accepts protocol-relative URLs."
  (when text
    ; If we get non-URL things, like fragments, skip.
    (try 
    ; These will be found in a well-deliniated URL, so we can take the rest of the link.
    (when-let [url-text (cond
                    (.startsWith ^String text "//") (str "http:" text)
                    (.startsWith ^String text "http:") text
                    (.startsWith ^String text "https:") text
                    ; Ignore relative URLs, as they can't be DOIs or publisher links.
                    :default nil)]
      (new URL (URLDecoder/decode url-text "UTF-8")))
    (catch MalformedURLException e)
    (catch IllegalArgumentException e))))
    
(defn is-doi-url?
  "If the URL is a DOI, return the DOI as a string."
  [url-string]

  (let [url (href-to-url url-string)]
    (when url 
      (let [host (.getHost ^URL url)
            url-path (.getPath ^URL url)
            ; Drop leading slash.
            url-path (when-not (string/blank? url-path) (subs url-path 1))
            likely-doi (and host
                            url-path
                            (.contains host "doi.org")
                            (.startsWith url-path "10."))]
        (when likely-doi url-path)))))
    
(defn extract-a-hrefs-from-html [input]
    (let [links (-> input
            Jsoup/parse
            (.select "a[href]"))
          hrefs (keep #(.attr % "href") links)]
      (set hrefs)))

;From https://meta.wikimedia.org/wiki/List_of_Wikipedias#1.2B_articles
(def server-names {
  "en" "English"
  "sv" "Swedish"
  "nl" "Dutch"
  "de" "German"
  "fr" "French"
  "war" "Waray-Waray",
  "ru" "Russian"
  "ceb" "Cebuano"
  "it" "Italian"
  "es" "Spanish"
  "vi" "Vietnamese"
  "pl" "Polish"
  "ja" "Japanese"
  "pt" "Portuguese"
  "zh" "Chinese"
  "uk" "Ukrainian"
  "ca" "Catalan"
  "fa" "Persian"
  "no" "Norwegian (Bokmål)"
  "sh" "Serbo-croatian"
  "fi" "Finnish"
  "ar" "Arabic"
  "id" "Indonesian"
  "cs" "Czech"
  "sr" "Serbian"
  "ro" "Romanian"
  "ko" "Korean"
  "hu" "Hungarian"
  "ms" "Malay"
  "tr" "Turkish"
  "min" "Minangkabau"
  "eo" "Esperanto"
  "kk" "Kazakh"
  "eu" "Basque"
  "sk" "Slovak"
  "da" "Danish"
  "bg" "Bulgarian"
  "he" "Hebrew"
  "lt" "Lithuanian"
  "hy" "Armenian"
  "hr" "Croatian"
  "sl" "Slovenian"
  "et" "Estonian"
  "uz" "Uzbek"
  "gl" "Galician"
  "nn" "Norwegian (Nynorsk)"
  "vo" "Volapük"
  "la" "Latin"
  "simple" "Simple English"
  "el" "Greek"
  "hi" "Hindi"
  "az" "Azerbaijani"
  "th" "Thai"
  "ka" "Georgian"
  "ce" "Chechen"
  "oc" "Occitan"
  "be" "Belarusian"
  "mk" "Macedonian"
  "mg" "Malagasy"
  "new" "Newar"
  "ur" "Urdu"
  "tt" "Tatar"
  "ta" "Tamil"
  "pms" "Piedmontese"
  "cy" "Welsh"
  "tl" "Tagalog"
  "lv" "Latvian"
  "bs" "Bosnian"
  "te" "Telugu"
  "be-tasask" "Belarusian (Taraškievica)"
  "br" "Breton"
  "ht" "Haitian"
  "sq" "Albanian"
  "jv" "Javanese"
  "lb" "Luxembourgish"
  "mr" "Marathi"
  "is" "Icelandic"
  "ml" "Malayalam"
  "zh-yue" "Cantonese"
  "bn" "Bengali"
  "af" "Afrikaans"
  "ba" "Bashkir"
  "ga" "Irish"
  "pnb" "Western Punjabi"
  "cv" "Chuvash"
  "fy" "West Frisian"
  "lmo" "Lombard"
  "tg" "Tajik"
  "sco" "Scots"
  "my" "Burmese"
  "yo" "Yoruba"
  "an" "Aragonese"
  "ky" "Kirghiz"
  "sw" "Swahili"
  "io" "Ido"
  "ne" "Nepali"
  "gu" "Gujarati"
  "scn" "Sicilian"
  "bpy" "Bishnupriya Manipuri"
  "nds" "Low Saxon"
  "ku" "Kurdish"
  "ast" "Asturian"
  "qu" "Quechua"
  "als" "Alemannic"
  "su" "Sundanese"
  "pa" "Punjabi"
  "kn" "Kannada"
  "ckb" "Sorani"
  "ia" "Interlingua"
  "mn" "Mongolian"
  "nap" "Neapolitan"
  "bug" "Buginese"
  "arz" "Egyptian Arabic"
  "bat-smg" "Samogitian"
  "wa" "Walloon"
  "zh-min-nan" "Min Nan"
  "am" "Amharic"
  "map-bms" "Banyumasan"
  "gd" "Scottish Gaelic"
  "yi" "Yiddish"
  "mzn" "Mazandarani"
  "si" "Sinhalese"
  "fo" "Faroese"
  "bar" "Bavarian"
  "vec" "Venetian"
  "nah" "Nahuatl"
  "sah" "Sakha"
  "os" "Ossetian"
  "sa" "Sanskrit"
  "roa-tara" "Tarantino"
  "li" "Limburgish"
  "hsb" "Upper Sorbian"
  "or" "Oriya"
  "pam" "Kapampangan"
  "mrj" "Hill Mari"
  "mhr" "Meadow Mari"
  "se" "Northern Sami"
  "mi" "Maori"
  "ilo" "Ilokano"
  "hif" "Fiji Hindi"
  "bcl" "Central Bicolano"
  "gan" "Gan"
  "rue" "Rusyn"
  "ps" "Pashto"
  "glk" "Gilaki"
  "nds-nl" "Dutch Low Saxon"
  "bo" "Tibetan"
  "vls" "West Flemish"
  "diq" "Zazaki"
  "fiu-vro" "Võro"
  "xmf" "Mingrelian"
  "tk" "Turkmen"
  "gv" "Manx"
  "sc" "Sardinian"
  "co" "Corsican"
  "csb" "Kashubian"
  "hak" "Hakka"
  "km" "Khmer"
  "kv" "Komi"
  "vep" "Vepsian"
  "zea" "Zeelandic"
  "crh" "Crimean Tatar"
  "zh-classical" "Classical Chinese"
  "frr" "North Frisian"
  "eml" "Emilian-Romagnol"
  "ay" "Aymara"
  "stq" "Saterland Frisian"
  "udm" "Udmurt"
  "wuu" "Wu"
  "nrm" "Norman"
  "kw" "Cornish"
  "rm" "Romansh"
  "szl" "Silesian"
  "so" "Somali"
  "koi" "Komi-Permyak"
  "as" "Assamese"
  "lad" "Ladino"
  "mt" "Maltese"
  "fur" "Friulian"
  "dv" "Divehi"
  "gn" "Guarani"
  "dsb" "Lower Sorbian"
  "pcd" "Picard"
  "ie" "Interlingue"
  "sd" "Sindhi"
  "lij" "Ligurian"
  "cbk-zam" "Zamboanga Chavacano"
  "cdo" "Min Dong"
  "ksh" "Ripuarian"
  "ext" "Extremaduran"
  "mwl" "Mirandese"
  "gag" "Gagauz"
  "ang" "Anglo Saxon"
  "ace" "Acehnese"
  "ug" "Uyghur"
  "pi" "Pali"
  "pag" "Pangasinan"
  "nv" "Navajo"
  "frp" "Franco Provençal/Arpitan"
  "lez" "Lezgian"
  "sn" "Shona"
  "kab" "Kabyle"
  "ln" "Lingala"
  "pfl" "Palatinate German"
  "myv" "Erzya"
  "xal" "Kalmyk"
  "krc" "Karachay-Balkar"
  "haw" "Hawaiian"
  "rw" "Kinyarwanda"
  "pdc" "Pennsylvania German"
  "kaa" "Karakalpak"
  "to" "Tongan"
  "kl" "Greenlandic"
  "arc" "Aramaic"
  "nov" "Novial"
  "kbd" "Kabardian Circassian"
  "av" "Avar"
  "bxr" "Buryat (Russia)"
  "lo" "Lao"
  "bjn" "Banjar"
  "ha" "Hausa"
  "tet" "Tetum"
  "tpi" "Tok Pisin"
  "na" "Nauruan"
  "pap" "Papiamentu"
  "lbe" "Lak"
  "jbo" "Lojban"
  "ty" "Tahitian"
  "mdf" "Moksha"
  "roa-rup" "Aromanian"
  "wo" "Wolof"
  "tyv" "Tuvan"
  "ig" "Igbo"
  "srn" "Sranan"
  "nso" "Northern Sotho"
  "kg" "Kongo"
  "ab" "Abkhazian"
  "ltg" "Latgalian"
  "zu" "Zulu"
  "om" "Oromo"
  "chy" "Cheyenne"
  "za" "Zhuang"
  "cu" "Old Church Slavonic"
  "rmy" "Romani"
  "tw" "Twi"
  "tn" "Tswana"
  "chr" "Cherokee"
  "pih" "Norfolk"
  "mai" "Maithili"
  "got" "Gothic"
  "bi" "Bislama"
  "xh" "Xhosa"
  "sm" "Samoan"
  "ss" "Swati"
  "mo" "Moldovan"
  "rn" "Kirundi"
  "ki" "Kikuyu"
  "pnt" "Pontic"
  "bm" "Bambara"
  "iu" "Inuktitut"
  "ee" "Ewe"
  "lg" "Luganda"
  "ts" "Tsonga"
  "fj" "Fijian"
  "ak" "Akan"
  "ik" "Inupiak"
  "st" "Sesotho"
  "sg" "Sango"
  "ff" "Fula"
  "dz" "Dzongkha"
  "ny" "Chichewa"
  "ch" "Chamorro"
  "ti" "Tigrinya"
  "ve" "Venda"
  "ks" "Kashmiri"
  "tum" "Tumbuka"
  "cr" "Cree"
  "ng" "Ndonga"
  "cho" "Choctaw"
  "kj" "Kuanyama"
  "mh" "Marshallese"
  "ho" "Hiri Motu"
  "ii" "Sichuan Yi"
  "aa" "Afar"
  "mus" "Muscogee"
  "hz" "Herero"
  "kr" "Kanuri"})

(defn server-name [server]
  (let [subdomain (first (.split ^String server "\\."))]
    (str (get server-names subdomain subdomain) " Wikipedia")))